var input = document.getElementById("exampleEmailInput");
var list;
new Awesomplete(input, {
	list: [
    "Carrie ",
    "Changing Lanes ",
    "Amen. ",
    "Full Frontal ",
    "Narc ",
    "One Hour Photo ",
    "Roger Dodger ",
    "About a Boy ",
    "Malevolent ",
    "A Walk to Remember ",
    "My Big Fat Greek Weddin",
    "Catch Me If You Can ",
    "Lilo & Stitch ",
    "Paid in Full ",
    "The Hard Word ",
    "Cypher ",
    "Austin Powers in Goldmember ",
    "Unfaithful ",
    "Balto: Wolf Quest ",
    "Star Wars: Episode II - Attack of the Clone",
    "Queen of the Damned ",
    "xX",
    "The Santa Clause ",
    "Spy Kids 2: Island of Lost Dreams ",
    "Road to Perdition ",
    "Die Another Day ",
    "Star Trek: Nemesis ",
    "Drumline ",
    "Hart's War ",
    "40 Days and 40 Nights ",
    "Red Dragon ",
    "The Count of Monte Crist",
    "Ghost Ship ",
    "Men in Black II ",
    "The Bourne Identity ",
    "The Transporter ",
    "Phone Booth ",
    "Van Wilder ",
    "Treasure Planet ",
    "Minority Report ",
    "Cabin Fever ",
    "The Lord of the Rings: The Two Towers ",
    "Ice Age ",
    "Gangs of New York ",
    "Signs ",
    "John Q ",
    "K-19: The Widowmaker ",
    "The Time Machine ",
    "The Ring ",
    "The Scorpion King"


  ]
});
